server:
  port: 10000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.113.128:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf: #关闭thymeleaf缓存
    cache: false
  redis:
    host: 192.168.113.128
    port: 6379
  cache:
    type: redis   #配置缓存类型
    redis:
      time-to-live: 3600000   # 1小时
  session:
    store-type: redis  #配置session存储到redis
#      use-key-prefix: true  #默认key使用前缀
#      cache-null-values: true  #默认会缓存空值（解决缓存穿透）
#      key-prefix: CACHE_     默认分区名为前缀
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置线程池
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10






