###创建映射
PUT http://192.168.113.128:9200/my_index
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "age": {
        "type": "integer"
      },
      "name": {
        "type": "text"
      },
      "email": {
        "type": "keyword"
      }
    }
  }
}

###查看映射
GET http://192.168.113.128:9200/my_index

### 添加映射字段，index用于控制字段是否参与检索(默认true)
PUT http://192.168.113.128:9200/my_index/_mapping
Content-Type: application/json

{
  "properties": {
    "hobby": {
      "type": "text",
      "index": false
    }
  }
}





























