###创建映射
PUT http://192.168.113.128:9200/my_index
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "age": {
        "type": "integer"
      },
      "name": {
        "type": "text"
      },
      "email": {
        "type": "keyword"
      }
    }
  }
}

###查看映射
GET http://192.168.113.128:9200/my_index

### 添加映射字段，index用于控制字段是否参与检索(默认true)
PUT http://192.168.113.128:9200/my_index/_mapping
Content-Type: application/json

{
  "properties": {
    "hobby": {
      "type": "text",
      "index": false
    }
  }
}

### 修改映射，es不支持修改映射，只能创建新索引再重新迁移数据
### 创建新索引
PUT http://192.168.113.128:9200/newbank
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "account_number": {
        "type": "long"
      },
      "address": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "age": {
        "type": "integer"
      },
      "balance": {
        "type": "long"
      },
      "city": {
        "type": "keyword"
      },
      "email": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "employer": {
        "type": "keyword"
      },
      "firstname": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "gender": {
        "type": "keyword"
      },
      "lastname": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "state": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  }
}

###迁移数据,新版本es去除了type
POST http://192.168.113.128:9200/_reindex
Content-Type: application/json

{
  "source": {
    "index": "bank",
    "type": "account"
  },
  "dest": {
    "index": "newbank"
  }
}

###
GET http://192.168.113.128:9200/newbank/_search























