###检索所有，并按照account_number升序排列
GET http://192.168.113.128:9200/bank/_search?q=*&sort=account_number:asc

###
GET http://192.168.113.128:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "account_number": {
        "order": "desc"
      }
    }
  ]
}

### QueryDSL基本使用
GET http://192.168.113.128:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "sort": {
    "balance": {
      "order": "desc"
    }
  },
  "from": 0,
  "size": 2,
  "_source": ["balance","age"]
}

### match全文检索-按照评分排序，对检索条件分词匹配
GET http://192.168.113.128:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "account_number": 20
    }
  }
}

### match_phrase 短语匹配(不进行分词)
GET http://192.168.113.128:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "address": "mill lane"
    }
  }
}

### multi_match 多字段匹配
GET http://192.168.113.128:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "multi_match": {
      "query": "mill",
      "fields": ["state","address"]
    }
  }
}

### bool复合查询
GET http://192.168.113.128:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [{
        "match": {
          "address": "mill"
        }
      }],
      "must_not": [{
        "match": {
          "age": 18
        }
      }],
      "should": [{
        "match": {
          "lastname": "wallence"
        }
      }]
    }
  }
}












