spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.113.128:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /
    #开启发送端确认
    publisher-confirms: true
    #开启消息传递到队列的确认
    publisher-returns: true
    #只要抵达队列，以异步发送优先回调我们这个returnconfirm
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual #开启手动消费消息，默认是自动ack
  thymeleaf:
    cache: false
  redis:
    host: 192.168.113.128
  session:
    store-type: redis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000


#配置线程池
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10