spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.113.128:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /
    #开启发送端确认
    publisher-confirms: true
    #开启消息传递到队列的确认
    publisher-returns: true
    template:
      mandatory: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000
