server:
  port: 12000

spring:
  application:
    name: gulimall-search

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.113.128
  session:
    store-type: redis
es:
  config:
    hostname: "192.168.113.128"
    port: 9200
    scheme: "http"