server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url, baidu
        - id: ware_route
          uri: lb://gulimall-ware #负载均衡到nacos的注册中心中的gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gulimall-member #负载均衡到nacos的注册中心中的gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party #负载均衡到nacos的注册中心中的gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://gulimall-product #负载均衡到nacos的注册中心中的gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast #负载均衡到nacos的注册中心中的renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall_host_route
          uri: lb://gulimall-product #前台
          predicates:
          - Host=localhost,item.localhost

        - id: gulimall_search_route
          uri: lb://gulimall-search #前台搜索页
          predicates:
          - Host=search.localhost

        - id: gulimall_auth_server_route
          uri: lb://gulimall-auth-server #登录页面
          predicates:
          - Host=auth.localhost
        - id: gulimall_cart_route
          uri: lb://gulimall-cart #购物车
          predicates:
          - Host=cart.localhost
















