server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: cookie_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

